export default {
  'IMAGE': 'IMAGE',
  'AUDIO': 'AUDIO',
  'VIDEO': 'VIDEO',
  'DOCUMENT': 'DOCUMENT',
  'INTERACTIVE': 'INTERACTIVE',
}

export const RawMediaTypes = {
  'INTERACTIVE_ANIMATION': 'INTERACTIVE_ANIMATION',
  'INTERACTIVE_SIMULATION': 'INTERACTIVE_SIMULATION',
  'INTERACTIVE_WHITEBOARD': 'INTERACTIVE_WHITEBOARD',
  'TEXT_BOOK': 'TEXT_BOOK',
  'TEXT_CHAPTER': 'TEXT_CHAPTER',
  'TEXT_DOCUMENT': 'TEXT_DOCUMENT',
  'TEXT_PASSAGE': 'TEXT_PASSAGE',
  'TEXT_REFERENCE': 'TEXT_REFERENCE',
  'TEXT_WEBSITE': 'TEXT_WEBSITE',
  'MEDIA_AUDIO': 'MEDIA_AUDIO',
  'MEDIA_IMAGES_VISUALS': 'MEDIA_IMAGES_VISUALS',
  'MEDIA_VIDEO': 'MEDIA_VIDEO'
}