# run workflow on creating a semver tag and on every push to develop branch
on:
  push:
    branches:
      - develop
      - staging
    tags:
      - 'v*.*.*'

# build the image and push it to ghcr.io
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - # checkout code
        name: Checkout code
        uses: actions/checkout@v3

      - # set up node 18
        name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - # install node dependencies
        name: Install Node Dependencies
        run: npm install

      - # build with node
        name: Build with Node
        run: npm run build:${{ github.ref_name }}

      - # login to ghcr.io
        name: Log in to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - # determine image tags
        name: Determine image tags
        id: determine_image_tags
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]
          then
            tag=${GITHUB_REF:10}
            no_v=${tag//v/}
            echo "TAG=${no_v}" >> $GITHUB_OUTPUT
          else
            git_branch=${GITHUB_REF#refs/heads/}
            if [ "$git_branch" == 'develop' ]
            then
              echo "TAG=dev" >> $GITHUB_OUTPUT
            elif [ "$git_branch" == 'staging' ]
            then
              echo "TAG=stg" >> $GITHUB_OUTPUT
            fi
          fi

      - # create git version variables
        name: Set Versions
        uses: actions/github-script@v6
        id: set_git_version
        with:
          script: |
            const tag = context.ref.substring(10)
            const no_v = tag.replace('v', '')
            core.setOutput('tag', tag)
            core.setOutput('no-v', no_v)

      - # build image and push it
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{steps.determine_image_tags.outputs.TAG}}
            ghcr.io/${{ github.repository }}:${{steps.determine_image_tags.outputs.TAG}}-${{ github.run_number }}
          build-args: |
            BUILD_NR: ${{ github.run_number }}
            BUILD_TIMESTAMP: ${{ github.event.repository.updated_at}}
            BRANCH: ${{ github.ref_name }}
